export * from "./illustrator/Illustrator";
export * from "./animation/IllustratorAnimation";
export * from "./layer/LayerManager";
export * from "./layer/LayerUtils";
export * from "./utils/IllustratorCollection";
export * from "./layer/Layer";
export * from "./utils/ColorUtil";
export * as Tools from "./toolbox/exports";
export * from "./colors/ColorSwatches";
export * from "./colors/Colors";
export * from "./colors/IllustratorColor";
export * from "./image/ImageLoader";
export * from "./image/IllustratorImage";
export * from "./image/IllustratorImageManager";
export * from "./layer/LayerTools";
export * as SkCanvas from "@napi-rs/canvas";
export * as SkImage from "@napi-rs/image";

// export tools individually due to docgen issue
export * from "./toolbox/image/Image";
export * from "./toolbox/base/ToolBox";
export * from "./toolbox/base/BaseShapeTool";
export * from "./toolbox/color/BackgroundColor";
export * from "./toolbox/text/Text";
export * from "./toolbox/filters/Filter";
export * from "./toolbox/filters/Shadow";
export * from "./toolbox/filters/Sharpen";
export * from "./toolbox/filters/ConvolutionFilter";
export * from "./toolbox/shapes/Ellipse";
export * from "./toolbox/transform/Transform";
export * from "./toolbox/shapes/Line";
export * from "./toolbox/shapes/Rectangle";
export * from "./toolbox/eraser/Eraser";
